### ISSUE TITLE
error

### ISSUE THREAD

**Issue by superentropic** [kvmclgi/Dark-and-Darker-Source#1]

**Comment by idiosyncretic** [comment]
fixed dw

**Comment by idiosyncretic** [comment]
![image](https://github.com/kvmclgi/Dark-and-Darker-Source/assets/61183697/8135e095-c6e4-45fb-8998-5a8fec97bef6)

**Comment by idiosyncretic** [comment]
Dnd.dll isnt there

**Comment by idiosyncretic** [comment]
the dll file gets immediately moved or removed after building the project each time
